apiVersion: v1
kind: Service
metadata:
  name: poker-frontend
  labels:
    app: poker-app
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: poker-app
    component: frontend
