apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: temperature-converter
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-converter
      component: backend
  template:
    metadata:
      labels:
        app: temperature-converter
        component: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/dsvibe-487714/temperature-backend:latest
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: PORT
              value: "50051"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
