apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: temperature-converter
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-converter
      component: frontend
  template:
    metadata:
      labels:
        app: temperature-converter
        component: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/dsvibe-487714/temperature-frontend:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
