// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/temperature.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemperatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureRequest) Reset() {
	*x = TemperatureRequest{}
	mi := &file_proto_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureRequest) ProtoMessage() {}

func (x *TemperatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureRequest.ProtoReflect.Descriptor instead.
func (*TemperatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *TemperatureRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TemperatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureResponse) Reset() {
	*x = TemperatureResponse{}
	mi := &file_proto_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureResponse) ProtoMessage() {}

func (x *TemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureResponse.ProtoReflect.Descriptor instead.
func (*TemperatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *TemperatureResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TemperatureResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_proto_temperature_proto protoreflect.FileDescriptor

const file_proto_temperature_proto_rawDesc = "" +
	"\n" +
	"\x17proto/temperature.proto\x12\vtemperature\"*\n" +
	"\x12TemperatureRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"?\n" +
	"\x13TemperatureResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit2\xc7\x01\n" +
	"\x14TemperatureConverter\x12U\n" +
	"\x10ConvertToCelsius\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\x12X\n" +
	"\x13ConvertToFahrenheit\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_temperature_proto_rawDescOnce sync.Once
	file_proto_temperature_proto_rawDescData []byte
)

func file_proto_temperature_proto_rawDescGZIP() []byte {
	file_proto_temperature_proto_rawDescOnce.Do(func() {
		file_proto_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_temperature_proto_rawDesc), len(file_proto_temperature_proto_rawDesc)))
	})
	return file_proto_temperature_proto_rawDescData
}

var file_proto_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_temperature_proto_goTypes = []any{
	(*TemperatureRequest)(nil),  // 0: temperature.TemperatureRequest
	(*TemperatureResponse)(nil), // 1: temperature.TemperatureResponse
}
var file_proto_temperature_proto_depIdxs = []int32{
	0, // 0: temperature.TemperatureConverter.ConvertToCelsius:input_type -> temperature.TemperatureRequest
	0, // 1: temperature.TemperatureConverter.ConvertToFahrenheit:input_type -> temperature.TemperatureRequest
	1, // 2: temperature.TemperatureConverter.ConvertToCelsius:output_type -> temperature.TemperatureResponse
	1, // 3: temperature.TemperatureConverter.ConvertToFahrenheit:output_type -> temperature.TemperatureResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_temperature_proto_init() }
func file_proto_temperature_proto_init() {
	if File_proto_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_temperature_proto_rawDesc), len(file_proto_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_temperature_proto_goTypes,
		DependencyIndexes: file_proto_temperature_proto_depIdxs,
		MessageInfos:      file_proto_temperature_proto_msgTypes,
	}.Build()
	File_proto_temperature_proto = out.File
	file_proto_temperature_proto_goTypes = nil
	file_proto_temperature_proto_depIdxs = nil
}
