// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/temperature.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperatureConverter_ConvertToCelsius_FullMethodName    = "/temperature.TemperatureConverter/ConvertToCelsius"
	TemperatureConverter_ConvertToFahrenheit_FullMethodName = "/temperature.TemperatureConverter/ConvertToFahrenheit"
)

// TemperatureConverterClient is the client API for TemperatureConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemperatureConverterClient interface {
	ConvertToCelsius(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
	ConvertToFahrenheit(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
}

type temperatureConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureConverterClient(cc grpc.ClientConnInterface) TemperatureConverterClient {
	return &temperatureConverterClient{cc}
}

func (c *temperatureConverterClient) ConvertToCelsius(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureConverter_ConvertToCelsius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureConverterClient) ConvertToFahrenheit(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureConverter_ConvertToFahrenheit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperatureConverterServer is the server API for TemperatureConverter service.
// All implementations must embed UnimplementedTemperatureConverterServer
// for forward compatibility.
type TemperatureConverterServer interface {
	ConvertToCelsius(context.Context, *TemperatureRequest) (*TemperatureResponse, error)
	ConvertToFahrenheit(context.Context, *TemperatureRequest) (*TemperatureResponse, error)
	mustEmbedUnimplementedTemperatureConverterServer()
}

// UnimplementedTemperatureConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperatureConverterServer struct{}

func (UnimplementedTemperatureConverterServer) ConvertToCelsius(context.Context, *TemperatureRequest) (*TemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertToCelsius not implemented")
}
func (UnimplementedTemperatureConverterServer) ConvertToFahrenheit(context.Context, *TemperatureRequest) (*TemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertToFahrenheit not implemented")
}
func (UnimplementedTemperatureConverterServer) mustEmbedUnimplementedTemperatureConverterServer() {}
func (UnimplementedTemperatureConverterServer) testEmbeddedByValue()                              {}

// UnsafeTemperatureConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureConverterServer will
// result in compilation errors.
type UnsafeTemperatureConverterServer interface {
	mustEmbedUnimplementedTemperatureConverterServer()
}

func RegisterTemperatureConverterServer(s grpc.ServiceRegistrar, srv TemperatureConverterServer) {
	// If the following call panics, it indicates UnimplementedTemperatureConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperatureConverter_ServiceDesc, srv)
}

func _TemperatureConverter_ConvertToCelsius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertToCelsius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureConverter_ConvertToCelsius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertToCelsius(ctx, req.(*TemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureConverter_ConvertToFahrenheit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertToFahrenheit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureConverter_ConvertToFahrenheit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertToFahrenheit(ctx, req.(*TemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperatureConverter_ServiceDesc is the grpc.ServiceDesc for TemperatureConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperature.TemperatureConverter",
	HandlerType: (*TemperatureConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToCelsius",
			Handler:    _TemperatureConverter_ConvertToCelsius_Handler,
		},
		{
			MethodName: "ConvertToFahrenheit",
			Handler:    _TemperatureConverter_ConvertToFahrenheit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/temperature.proto",
}
